### ISSUE TITLE
Helmholtz pitch notation

### ISSUE THREAD

**Issue by zmoon** [zmoon/PyABC2#38]
https://en.wikipedia.org/wiki/Helmholtz_pitch_notation

Should maybe support converting pitches to (+ from?) strings of this format, as an alternative to SPN.

**Comment by zmoon** [comment]
@mccalluc I think if you comment on this issue I can assign it to you, if you still want.

**Comment by mccalluc** [comment]
Sure, this looks like something I should be able to do. Thanks!
